### PR TITLE
:space_invader: added mixin and examples for a spinner field

### PR DESCRIPTION
**Pull request by mgiraldo**
also made the style a general mixin (no longer only button-specific)

### CODE REVIEW

**Comment by ablwr** [comment]
Should the first in the series appear with orange highlighting? 

screen shot 2017-04-25 at 1 02 05 pm 2

**Comment by mgiraldo** [comment]
the JS there is very basic... it just starts the spin on change and waits two seconds then removes... some of the examples are a bit more elaborate, disabling the fields and such... in short: the JS is for entertainment purposes only... what browser are you using?

**Comment by ablwr** [comment]
Very entertaining! Chrome.

**Comment by ablwr** [comment]
Firefox does the same and a little bit in the Topics category too (the orange is not covered, which is maybe your intent?).

**Comment by mgiraldo** [comment]
try again (moar commitz)

**Comment by ablwr** [comment]
arigatou. Chrome is consistent across all spinners; although still present in Firefox.

**Pull request merged**
