### PR TITLE
Remove `a:focus` background-color change

### PR DESCRIPTION
**Pull request by siberry**

### CODE REVIEW

**Comment by siberry** [comment]
> Update the readme and package.json version. Do you have access to deploy to npm?

I do not have access to deploy the npm I am pretty sure. So, this should be patch update?

**Comment by EdwinGuzman** [comment]
Yes, `0.1.38` is the next version. I can publish to npm once this is merged.

**Comment by EdwinGuzman** [comment]
I just realized, why are you using a fork of this?...

**Comment by siberry** [comment]
I had forked it awhile ago. I realized that when I opened the PR. Fixing that now.

**Comment by siberry** [comment]
It's not `0.1.37`?

**Pull request closed without merging**
