### PR TITLE
Search improvement

### PR DESCRIPTION
**Pull request by ricardoom**
Gents,
take a look at this and let me know if you still see the mis-alignment on the radio drop down.

### CODE REVIEW

**Comment by ricardoom** [comment]
I can resolve the conflicts if the layout is working as expected.

**Comment by mgiraldo** [comment]
other than the conflicts, has an alignment issue:

image

and button needs to have a box or else it “disappears” in the background:

image

**Comment by ricardoom** [comment]
Weird... still not seeing this jogging. in a few different browsers...
ugh.

**Comment by ricardoom** [comment]
Due to major changes on the master branch. going to close this PR and integrate work from new master, as its going to be a pain in the neck to reconcile the new changes w/ this PR.

**Pull request closed without merging**
