### PR TITLE
#233 Hotfix

### PR DESCRIPTION
**Pull request by ricardoom**
- add vendor prefixes to the checkbox transform

### CODE REVIEW

**Comment by ricardoom** [comment]
🔥

**Comment by EdwinGuzman** [comment]
Looks good in Safari, FF, and Chrome. Just minor detail:

left = PR, right = design toolkit now
screen shot 2017-10-03 at 12 52 15 pm

The text for the `language` label sits right at the top of the box and is not centered with the text.

**Comment by ricardoom** [comment]
eagle eyes @EdwinGuzman  👀 
screen shot 2017-10-03 at 1 18 51 pm

**Comment by EdwinGuzman** [comment]
:hawk-emoji:

**Pull request merged**
