### PR TITLE
Header improve

### PR DESCRIPTION
**Pull request by ricardoom**
@mgiraldo / @EdwinGuzman dig these modest changes to the header...

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
I'm digging the extra, roomy feeling, but it does feel a bit empty in the middle.

**Comment by ricardoom** [comment]
horror vaccui rules my world

**Comment by EdwinGuzman** [comment]
Cool. Ultimately, it's your decision. The update is good, but either one is 👍

**Comment by mgiraldo** [comment]
logo is **enormous** now. this is the comparison with the current one:

image

it's basically the same size. let's not worry about pushback before the pushback. let's worry about having a great header and i think the huge logo detracts from that. 

i am not seeing search bar changes. are those not in? this is what i see there:

image

**Comment by ricardoom** [comment]
re: search. I didn’t send that change along.
re: logo. so be it.  

Ricardo E. Gálvez | The New York Public Library
Visual Designer

Digital Experience
212.621.0521
2nd Floor-South Court
Stephen A. Schwarzman Building
476 Fifth Ave.
New York, NY 10018-2788
ricardogalvez@nypl.org


Inspiring Lifelong Learning | Advancing Knowledge | Strengthening our Communities

**Pull request closed without merging**
