### PR TITLE
Visible focus

### PR DESCRIPTION
**Pull request by wlla**
Drafted preliminary documentation for visible focus standards.

### CODE REVIEW

**Comment by ktp242** [comment]
wow Willa made a PR!!! Looks nice!
I am curious about how to document in `design-toolkit/docs/_sections`
I see some files are `.md` some are `.html`

**Comment by ricardoom** [comment]
@ktp242 please approve or request changes to this PR.

**Comment by ktp242** [comment]
Do we have a convention for documentation? Should we use `.md` or `.html`?

**Comment by EdwinGuzman** [comment]
It doesn't matter too much because the rendering engine will pick up either and correctly generate the file we want. But, for consistency, we should pick on or the other. But, there is no convention for regarding the type of file for this repo yet so that can be settled later.

**Comment by ricardoom** [comment]
I think its best to put any conventional documentation in a .md file, where there are .html files those particular files are heavy w/ html / js / css examples. 

To @EdwinGuzman's point. The convention should be, as such. Basic documentation should be in a .md file and but if there are code examples, we should use .html files. Hope that clears up any questions.

**Comment by ktp242** [comment]
@ricardoom I like your approach! Thanks for the answer. We can definitely settle it later, but I just felt I need to ask for clarifying :-)

**Comment by EdwinGuzman** [comment]
@wlla feel free to merge whenever you want.

**Pull request merged**
