### PR TITLE
227 filter modal improve

### PR DESCRIPTION
**Pull request by ricardoom**
Modal improvements. 
please run locally and make sure the close button is working as expected. Namely visible on small screens. Try running off an ngrok url and test on your device if you have time.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
This is what I see locally:
screen shot 2017-09-25 at 3 26 49 pm

It get's chopped off at the top.

**Comment by ricardoom** [comment]
@EdwinGuzman Chrome yeah?

**Comment by EdwinGuzman** [comment]
Yes.

**Comment by ricardoom** [comment]
must needs more works...

**Pull request closed without merging**
