### PR TITLE
added moar space to the main search

### LINKED ISSUE #125: put button in facet remove outside of the strong tag

### PR DESCRIPTION
**Pull request by mgiraldo**
based on @ricardoom suggestions added space to the main search and removed id references in sass / rem-ified a bunch / fixes #125

there's a 1px vertical offset between the search button and text field which drives me a bit nuts but can be left alone for now (if someone knows how to align that, you're welcome to try it)

see screenshots:
image

image

### CODE REVIEW

**Comment by mgiraldo** [comment]
re search button/text align: i fixed it 💪

**Comment by mgiraldo** [comment]
someone wanna give this a look and merge?

**Comment by ricardoom** [comment]
Looks good...
@EdwinGuzman ?

**Comment by EdwinGuzman** [comment]
Yes! Looks very good.

**Comment by EdwinGuzman** [comment]
The `nypl-` prefix and the rem update is good too. Thanks.

**Pull request merged**
