### PR TITLE
:space_invader: added the checked state to the terms checkbox

### PR DESCRIPTION
**Pull request by mgiraldo**

### CODE REVIEW

**Comment by ablwr** [comment]
Should the example work?

**Comment by ablwr** [comment]
Sorry, let me be more helpful. In the console, I get this flag raised: `Uncaught SyntaxError: missing ) after argument list` for `header.js:297`

**Comment by mgiraldo** [comment]
i dont get that error 🤔

but yes, example should work

**Comment by ablwr** [comment]
How strange!

Jekyll is upset in this way:
```
[2017-04-26 16:37:15] ERROR `/css/example-styles.css.map' not found.
[2017-04-26 16:37:15] ERROR `/css/docs.css.map' not found.
```

🤔

**Comment by mgiraldo** [comment]
the map error happens because the scss files are in a folder outside of the docs (outside of jekyll territory)... 

¯\_(ツ)_/¯

**Comment by mgiraldo** [comment]
you ruined it!

but i fixed it now in 22f4057d4ad33b9cef6fa3f4167eeb644fd1937c 💪

**Comment by ablwr** [comment]
Wasn't me! 😆

**Pull request merged**
