### PR TITLE
new order for omnibox fields / fixes #150

### LINKED ISSUE #150: change the order of the omni box elements
to: text field - filters - button

### PR DESCRIPTION
**Pull request by mgiraldo**
new order for omnibox fields / fixes #150

### CODE REVIEW

**Comment by ablwr** [comment]
Oh bummer, I was really starting to like the "search | fields | TEXT" pattern. Was this from the accessibility review or the demo audience?

**Comment by mgiraldo** [comment]
request from tony

**Comment by EdwinGuzman** [comment]
I like this update and prefer it over the other one. But, I'd like to have accessibility and user testing backing up changes rather than Tony. Not for me to say though.

**Comment by mgiraldo** [comment]
previous one was accessible... this is a reordering of elements... also accessible... [user research points](http://uxmovement.com/forms/left-search-buttons-perform-faster-than-right-ones/) to the previous configuration being better, though

this change is not under discussion right now

**Pull request merged**
