### PR TITLE
Hotfix field update

### PR DESCRIPTION
**Pull request by ricardoom**
please run and confirm its not all kinds of busted up. 
For comparison:
[https://drive.google.com/file/d/0B2LQIUUuUDJdcl9XSm56WDhFV0k/view?usp=sharing](https://drive.google.com/file/d/0B2LQIUUuUDJdcl9XSm56WDhFV0k/view?usp=sharing)

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
I think you linked the wrong comp.

PR looks good tho.

**Comment by ricardoom** [comment]
fixed the link. my bad. like i said. today I'm totally not on fire.

**Comment by ktp242** [comment]
Looks nice. I am wondering about the examples in the repo. Are we going to update them some time in the future to match the new designs?

**Comment by ricardoom** [comment]
@ktp242 could you clarify / specify? there are many patterns needing changing and updating. If you see something specifically that needs attention _nowish_ let me know...

**Comment by ablwr** [comment]
Tentative approval ... need to know who is making the final decision on the content here! Approved insomuch as it looks like the design.

**Pull request merged**
