### PR TITLE
:meat_on_bone: 

### PR DESCRIPTION
**Pull request by ricardoom**
minor updates after updating npm...guh

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
I didn't know you could make a specific version of `npm` a dependency in the project. I figured that'd be outside of that object in the config.

**Comment by EdwinGuzman** [comment]
Is this still opened?

**Comment by ricardoom** [comment]
It is still technically open. But I dont remember why I made this a PR...the only thing in here is that npm version thing, which was done automysteriously by npm....

**Comment by ricardoom** [comment]
I'm going to close for now.

**Pull request closed without merging**
